Implement buffer functionality
iot2tangle/Keepy pull request #6
Opened 2020-11-07 03:43 UTC by eduardopelitti

Configurable buffer to avoid Gateway Stream overload.

It depends on having a GW deployed that can receive a bundle of messages as an Array of objects instead of a single element.

2020-11-07 03:45 UTC, andyesp approved these changes

2020-11-10 21:39 UTC, eduardopelitti commented
commit [5d376c4](https://github.com/iot2tangle/Keepy/pull/6/commits/5d376c4fafb455e07848b541c8f6b884fb307921) closes #7

2020-11-10 22:14 UTC, andyesp requested changes

2020-11-10 22:14 UTC, andyesp commented on routes.js
> +              if (gatewayResponse.status === 400) {
We can use the same if here, and maybe we can also send the gateway status code to the console response message.
Example:
```
if (gatewayResponse.status === 400 || gatewayResponse.status === 404) {
  return response.status(500).send(`Error: Gateway response with ${gatewayResponse.statusCode}: ${gatewayResponse.statusText}`)
}
```

2020-11-10 22:15 UTC, andyesp requested changes

2020-11-10 22:15 UTC, andyesp commented on .env.example
> +GATEWAY_BUNDLE_URL=http://95.216.203.91:8080/bundle
Backend endpoint is `/bundle_data`

2020-11-11 16:23 UTC, demichele approved these changes

2020-11-11 16:24 UTC, demichele approved these changes

2020-11-11 16:29 UTC, merged